import { Platform, StyleSheet } from 'react-native';
import { mono, sans, Theme } from './theme';

export type Styles = ReturnType<typeof makeStyles>;

export function makeStyles(t: Theme) {
  const shadow = Platform.select({
    ios: {
      shadowColor: '#000',
      shadowOpacity: 0.1,
      shadowRadius: 12,
      shadowOffset: { width: 0, height: 6 },
    },
    android: { elevation: 2 },
    default: {},
  }) as object;

  return StyleSheet.create({
    root: { flex: 1, backgroundColor: t.paper },

    /* compact app header (safe-area padded from the screen) */
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 11,
      paddingHorizontal: 20,
      paddingBottom: 12,
      backgroundColor: t.surface,
      borderBottomWidth: 1,
      borderBottomColor: t.line,
    },
    mark: {
      width: 34,
      height: 34,
      borderRadius: 9,
      backgroundColor: t.brand,
      alignItems: 'center',
      justifyContent: 'center',
    },
    markText: { color: '#fff', fontWeight: '800', fontSize: 12, letterSpacing: -0.5 },
    wordmark: { fontWeight: '800', fontSize: 15, letterSpacing: -0.2, color: t.ink },
    wordmarkSub: { fontFamily: mono, fontSize: 8.5, letterSpacing: 2, color: t.inkFaint, marginTop: 2 },
    locPill: {
      marginLeft: 'auto',
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      backgroundColor: t.brandSoft,
      borderWidth: 1,
      borderColor: t.brand,
      borderRadius: 999,
      paddingHorizontal: 11,
      paddingVertical: 6,
    },
    locPillDot: { color: t.brand, fontSize: 11 },
    locPillText: { color: t.brandInk, fontSize: 12, fontWeight: '700' },
    locPillZip: { color: t.brandInk, fontFamily: mono, fontSize: 11, opacity: 0.8 },

    /* scroll body */
    scroll: { paddingHorizontal: 20, paddingTop: 22, paddingBottom: 40 },

    /* screen title block */
    screenTitle: { fontWeight: '800', fontSize: 26, lineHeight: 30, letterSpacing: -0.6, color: t.ink },
    screenTitleAccent: { color: t.brand },
    screenLede: { marginTop: 10, fontSize: 15, lineHeight: 22, color: t.inkSoft },
    eyebrow: {
      fontFamily: mono,
      fontSize: 10,
      letterSpacing: 2,
      color: t.inkFaint,
      marginTop: 26,
      marginBottom: 10,
    },

    /* this-week highlight (replaces the old scoreboard) */
    week: { marginTop: 22 },
    weekEyebrow: { fontFamily: mono, fontSize: 11, color: t.inkFaint, letterSpacing: 0.3, marginBottom: 8 },
    weekHead: { fontSize: 19, lineHeight: 26, fontWeight: '700', color: t.ink },
    weekSave: { color: t.gold, fontWeight: '800' },
    weekStore: { color: t.brand, fontWeight: '800' },
    weekSub: { marginTop: 8, fontSize: 13.5, lineHeight: 20, color: t.inkSoft },
    weekRule: { height: 1, backgroundColor: t.line, marginTop: 18 },

    /* segmented control */
    segment: {
      flexDirection: 'row',
      backgroundColor: t.surface2,
      borderWidth: 1,
      borderColor: t.line,
      borderRadius: 12,
      padding: 4,
      marginTop: 22,
      gap: 4,
    },
    segBtn: { flex: 1, borderRadius: 9, paddingVertical: 9, alignItems: 'center' },
    segBtnActive: { backgroundColor: t.brand },
    segText: { fontSize: 14, fontWeight: '700', color: t.inkSoft },
    segTextActive: { color: '#fff' },
    segCount: { fontFamily: mono, fontSize: 11, color: t.inkFaint, marginTop: 1 },
    segCountActive: { color: 'rgba(255,255,255,0.8)' },

    /* chips (deals + cheapest) */
    chipsRow: { gap: 9, paddingHorizontal: 18 },
    chip: {
      backgroundColor: t.surface,
      borderWidth: 1,
      borderColor: t.line,
      borderRadius: 12,
      paddingHorizontal: 14,
      paddingVertical: 12,
      minWidth: 158,
      gap: 3,
      ...shadow,
    },
    chipName: { fontSize: 13, color: t.inkSoft },
    chipPrice: { fontFamily: mono, fontWeight: '800', fontSize: 18, color: t.ink },
    chipUnit: { fontFamily: mono, fontSize: 11, color: t.inkFaint, fontWeight: '500' },
    chipStore: { fontFamily: mono, fontSize: 9.5, letterSpacing: 0.5, color: t.brand },

    /* store status */
    card: {
      marginTop: 18,
      backgroundColor: t.surface2,
      borderWidth: 1,
      borderColor: t.line,
      borderRadius: 14,
      padding: 16,
    },
    cardTitle: { fontSize: 11, letterSpacing: 0.5, fontWeight: '700', color: t.inkSoft, marginBottom: 12 },
    storeRow: { flexDirection: 'row', alignItems: 'center', gap: 10, paddingVertical: 6 },
    storeName: { fontWeight: '700', fontSize: 14.5, color: t.ink },
    storeLoc: { fontSize: 12, color: t.inkFaint, flexShrink: 1 },
    badgeLive: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      backgroundColor: t.brandSoft,
      borderWidth: 1,
      borderColor: t.live,
      borderRadius: 999,
      paddingHorizontal: 9,
      paddingVertical: 4,
    },
    liveDot: { width: 7, height: 7, borderRadius: 4, backgroundColor: t.live },
    badgeLiveText: { fontFamily: mono, fontSize: 10, letterSpacing: 0.5, color: t.live, fontWeight: '700' },
    badgePending: {
      backgroundColor: t.goldBg,
      borderWidth: 1,
      borderColor: t.goldLine,
      borderRadius: 999,
      paddingHorizontal: 9,
      paddingVertical: 4,
    },
    badgePendingText: { fontFamily: mono, fontSize: 10, letterSpacing: 0.5, color: t.gold, fontWeight: '700' },

    /* cut row */
    cutRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      backgroundColor: t.surface,
      borderWidth: 1,
      borderColor: t.line,
      borderRadius: 12,
      paddingHorizontal: 14,
      paddingVertical: 11,
      marginBottom: 8,
    },
    cutLeft: { flex: 1, gap: 3 },
    cutName: { fontFamily: sans.bold, fontSize: 14.5, color: t.ink },
    cutSave: { fontFamily: mono, fontSize: 11, color: t.brand, fontWeight: '700' },
    cutSaveMuted: { color: t.inkFaint, fontWeight: '600' },

    pillGroup: { flexDirection: 'row', gap: 7 },
    pill: {
      width: 72,
      borderRadius: 10,
      paddingVertical: 7,
      paddingHorizontal: 4,
      alignItems: 'center',
      gap: 1,
      borderWidth: 1,
    },
    pillWin: { backgroundColor: t.brandSoft, borderColor: t.brand },
    pillLose: { backgroundColor: t.surface2, borderColor: t.line },
    pillTie: { backgroundColor: t.surface2, borderColor: t.lineStrong },
    pillLabel: { fontSize: 10, color: t.inkSoft },
    pillPrice: { fontFamily: mono, fontWeight: '700', fontSize: 14, color: t.ink },
    pillPriceWin: { fontFamily: mono, fontWeight: '800', fontSize: 14, color: t.brand },
    pillPriceLose: { fontFamily: mono, fontWeight: '600', fontSize: 14, color: t.inkSoft },
    pillFlag: { fontFamily: mono, fontSize: 8.5, letterSpacing: 0.5, color: t.brand, fontWeight: '800' },
    pillFlagMuted: { fontFamily: mono, fontSize: 8.5, letterSpacing: 0.5, color: t.inkFaint, fontWeight: '700' },

    /* deals list */
    dealRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      backgroundColor: t.surface,
      borderWidth: 1,
      borderColor: t.line,
      borderRadius: 12,
      paddingHorizontal: 14,
      paddingVertical: 12,
      marginBottom: 8,
    },
    dealRank: {
      width: 30,
      height: 30,
      borderRadius: 8,
      backgroundColor: t.goldBg,
      borderWidth: 1,
      borderColor: t.goldLine,
      alignItems: 'center',
      justifyContent: 'center',
    },
    dealRankText: { fontFamily: mono, fontWeight: '800', fontSize: 13, color: t.gold },
    dealMid: { flex: 1, gap: 2 },
    dealCut: { fontSize: 14.5, fontWeight: '600', color: t.ink },
    dealMeta: { fontFamily: mono, fontSize: 11, color: t.inkSoft },
    dealMetaStore: { color: t.brand, fontWeight: '700' },
    dealSave: { alignItems: 'flex-end' },
    dealSaveNum: { fontFamily: mono, fontWeight: '800', fontSize: 15, color: t.gold },
    dealSaveUnit: { fontFamily: mono, fontSize: 9.5, color: t.inkFaint, letterSpacing: 0.5 },

    /* match note */
    noteCard: {
      marginTop: 20,
      backgroundColor: t.surface2,
      borderWidth: 1,
      borderColor: t.line,
      borderRadius: 12,
      padding: 15,
    },
    noteText: { fontSize: 13, lineHeight: 20, color: t.inkSoft },
    noteBold: { color: t.ink, fontWeight: '700' },

    /* vision */
    visionGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 12, marginTop: 14 },
    visionCard: {
      flexGrow: 1,
      flexBasis: '46%',
      backgroundColor: t.surface,
      borderWidth: 1,
      borderColor: t.line,
      borderRadius: 12,
      padding: 15,
    },
    visionLab: { fontFamily: mono, fontSize: 10, letterSpacing: 1.5, color: t.inkFaint, marginBottom: 6 },
    visionBody: { fontSize: 13.5, lineHeight: 20, color: t.inkSoft },

    /* location picker */
    gpsBtn: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 8,
      backgroundColor: t.brand,
      borderRadius: 12,
      paddingVertical: 13,
      marginTop: 18,
    },
    gpsBtnText: { color: '#fff', fontWeight: '700', fontSize: 14.5 },
    gpsError: { fontSize: 12.5, color: t.oxblood, marginTop: 8, textAlign: 'center' },
    orRow: { flexDirection: 'row', alignItems: 'center', gap: 10, marginVertical: 16 },
    orLine: { flex: 1, height: 1, backgroundColor: t.line },
    orText: { fontFamily: mono, fontSize: 10, letterSpacing: 1, color: t.inkFaint },
    pickRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
    pick: {
      borderWidth: 1,
      borderColor: t.line,
      backgroundColor: t.surface,
      borderRadius: 999,
      paddingHorizontal: 14,
      paddingVertical: 9,
    },
    pickActive: { backgroundColor: t.brandSoft, borderColor: t.brand },
    pickText: { fontSize: 13.5, color: t.inkSoft, fontWeight: '600' },
    pickTextActive: { color: t.brandInk, fontWeight: '700' },
    milesChip: {
      borderWidth: 1,
      borderColor: t.line,
      backgroundColor: t.surface,
      borderRadius: 10,
      paddingHorizontal: 14,
      paddingVertical: 10,
      alignItems: 'center',
      minWidth: 58,
    },
    milesChipActive: { backgroundColor: t.brand, borderColor: t.brand },
    milesNum: { fontFamily: mono, fontWeight: '800', fontSize: 15, color: t.ink },
    milesNumActive: { color: '#fff' },
    milesUnit: { fontFamily: mono, fontSize: 9, letterSpacing: 0.5, color: t.inkFaint },
    milesUnitActive: { color: 'rgba(255,255,255,0.8)' },

    /* nearby store row */
    nStore: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      backgroundColor: t.surface,
      borderWidth: 1,
      borderColor: t.line,
      borderRadius: 12,
      paddingHorizontal: 14,
      paddingVertical: 12,
      marginBottom: 8,
    },
    nStoreMid: { flex: 1, gap: 3 },
    nStoreName: { fontSize: 15, fontWeight: '700', color: t.ink },
    nStoreMeta: { fontSize: 12.5, color: t.inkFaint },
    nStoreNote: { fontFamily: mono, fontSize: 10.5, color: t.inkFaint, marginTop: 1 },
    nStoreHint: { fontFamily: mono, fontSize: 10.5, color: t.brand, fontWeight: '700', marginTop: 1 },
    nStoreRight: { alignItems: 'flex-end', gap: 5 },
    nMiles: { fontFamily: mono, fontWeight: '800', fontSize: 14, color: t.ink },
    nMilesUnit: { fontFamily: mono, fontSize: 9, color: t.inkFaint, letterSpacing: 0.5 },
    statusLive: { backgroundColor: t.brandSoft, borderColor: t.live, borderWidth: 1, borderRadius: 999, paddingHorizontal: 8, paddingVertical: 3 },
    statusLiveText: { fontFamily: mono, fontSize: 9, letterSpacing: 0.5, color: t.live, fontWeight: '700' },
    statusOnline: { backgroundColor: t.goldBg, borderColor: t.goldLine, borderWidth: 1, borderRadius: 999, paddingHorizontal: 8, paddingVertical: 3 },
    statusOnlineText: { fontFamily: mono, fontSize: 9, letterSpacing: 0.5, color: t.gold, fontWeight: '700' },
    statusReq: { backgroundColor: t.surface2, borderColor: t.line, borderWidth: 1, borderRadius: 999, paddingHorizontal: 8, paddingVertical: 3 },
    statusReqText: { fontFamily: mono, fontSize: 9, letterSpacing: 0.5, color: t.inkFaint, fontWeight: '700' },
    emptyNear: { fontSize: 13.5, color: t.inkSoft, textAlign: 'center', paddingVertical: 20, lineHeight: 20 },

    /* compare empty state */
    notice: {
      marginTop: 18,
      backgroundColor: t.goldBg,
      borderWidth: 1,
      borderColor: t.goldLine,
      borderRadius: 12,
      padding: 16,
    },
    noticeTitle: { fontWeight: '800', fontSize: 15, color: t.ink, marginBottom: 5 },
    noticeText: { fontSize: 13.5, lineHeight: 20, color: t.inkSoft },

    /* ===== Uber-Eats-style home feed ===== */
    feedHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: 18,
      paddingBottom: 10,
      backgroundColor: t.paper,
    },
    // brand + location stacked header
    feedHeaderWrap: { paddingHorizontal: 18, paddingBottom: 8, backgroundColor: t.paper },
    brandRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
    brandLockup: { flexDirection: 'row', alignItems: 'center', gap: 8 },
    markSm: { width: 27, height: 27, borderRadius: 7, backgroundColor: t.brand, alignItems: 'center', justifyContent: 'center' },
    markSmText: { color: '#fff', fontFamily: sans.xbold, fontSize: 10.5, letterSpacing: -0.3 },
    brandName: { fontFamily: sans.xbold, fontSize: 16.5, letterSpacing: -0.3, color: t.ink },
    dealsBtn: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 5,
      paddingHorizontal: 13,
      height: 34,
      borderRadius: 17,
      backgroundColor: t.goldBg,
      borderWidth: 1,
      borderColor: t.goldLine,
    },
    dealsBtnText: { color: t.gold, fontFamily: sans.bold, fontSize: 13 },
    feedAddr: { flexDirection: 'row', alignItems: 'center', gap: 5 },
    feedAddrPin: { fontSize: 10, color: t.brand, marginRight: 3 },
    feedAddrText: { fontSize: 18, fontWeight: '800', color: t.ink, letterSpacing: -0.3 },
    feedChevron: { fontSize: 13, color: t.ink, marginTop: 2 },
    bell: {
      marginLeft: 'auto',
      width: 40,
      height: 40,
      borderRadius: 20,
      backgroundColor: t.surface2,
      alignItems: 'center',
      justifyContent: 'center',
    },

    chipScroll: { paddingHorizontal: 18, gap: 8, paddingVertical: 4 },
    fchip: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      borderWidth: 1,
      borderColor: t.line,
      backgroundColor: t.surface,
      borderRadius: 999,
      paddingHorizontal: 15,
      paddingVertical: 9,
    },
    fchipActive: { backgroundColor: t.ink, borderColor: t.ink },
    fchipText: { fontSize: 14, fontWeight: '600', color: t.ink },
    fchipTextActive: { color: t.paper },

    tileScroll: { paddingHorizontal: 18, gap: 16, paddingVertical: 6 },
    tile: { alignItems: 'center', width: 64, gap: 6 },
    tileCircle: {
      width: 60,
      height: 60,
      borderRadius: 30,
      backgroundColor: t.surface2,
      alignItems: 'center',
      justifyContent: 'center',
    },
    tileCircleActive: { backgroundColor: t.brandSoft, borderWidth: 2, borderColor: t.brand },
    tileEmoji: { fontSize: 28 },
    tileLabel: { fontSize: 11.5, color: t.ink, fontWeight: '600', textAlign: 'center' },

    secHead: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: 18,
      marginTop: 22,
      marginBottom: 12,
    },
    secTitle: { fontFamily: sans.xbold, fontSize: 22, color: t.ink, letterSpacing: -0.5 },
    secArrow: {
      marginLeft: 'auto',
      width: 30,
      height: 30,
      borderRadius: 15,
      backgroundColor: t.surface2,
      alignItems: 'center',
      justifyContent: 'center',
    },

    /* deal carousel card */
    dealScroll: { paddingHorizontal: 18, gap: 14 },
    dcard: { width: 230 },
    dcardTop: {
      height: 120,
      borderRadius: 14,
      justifyContent: 'space-between',
      padding: 12,
      overflow: 'hidden',
    },
    dcardBadge: {
      alignSelf: 'flex-start',
      backgroundColor: '#D64545',
      borderRadius: 7,
      paddingHorizontal: 8,
      paddingVertical: 4,
    },
    dcardBadgeText: { color: '#fff', fontWeight: '800', fontSize: 12.5 },
    dcardEmoji: { fontSize: 46, alignSelf: 'flex-end' },
    dcardName: { marginTop: 9, fontSize: 15, fontWeight: '700', color: t.ink },
    dcardMeta: { marginTop: 2, fontSize: 13, color: t.inkSoft },
    dcardMetaStore: { color: t.brand, fontWeight: '700' },

    /* big store card */
    scard: { marginHorizontal: 18, marginBottom: 18 },
    scHeader: {
      height: 130,
      borderRadius: 16,
      padding: 14,
      justifyContent: 'space-between',
      overflow: 'hidden',
    },
    scTopRow: { flexDirection: 'row', alignItems: 'flex-start' },
    scPromo: {
      backgroundColor: '#D64545',
      borderRadius: 7,
      paddingHorizontal: 9,
      paddingVertical: 5,
    },
    scPromoText: { color: '#fff', fontWeight: '800', fontSize: 13 },
    scHeart: {
      marginLeft: 'auto',
      width: 34,
      height: 34,
      borderRadius: 17,
      backgroundColor: 'rgba(255,255,255,0.85)',
      alignItems: 'center',
      justifyContent: 'center',
    },
    scMono: { fontSize: 44, fontWeight: '900', color: 'rgba(255,255,255,0.9)', letterSpacing: -1 },
    scBody: { paddingTop: 11 },
    scName: { fontSize: 18, fontWeight: '800', color: t.ink, letterSpacing: -0.3 },
    scMetaRow: { flexDirection: 'row', alignItems: 'center', gap: 7, marginTop: 4 },
    scLiveDot: { width: 7, height: 7, borderRadius: 4, backgroundColor: t.live },
    scMeta: { fontSize: 13.5, color: t.inkSoft },
    scMetaStrong: { color: t.ink, fontWeight: '600' },
    scPrice: { marginTop: 7, fontSize: 14, color: t.ink },
    scPriceVal: { fontFamily: mono, fontWeight: '800', color: t.brand },
    scByReq: { marginTop: 7, fontSize: 13, color: t.inkFaint },
    scList: { marginTop: 10, gap: 2 },
    scListRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      paddingVertical: 5,
      borderTopWidth: 1,
      borderTopColor: t.line,
    },
    scListCat: { fontSize: 13, fontWeight: '700', color: t.ink, width: 96 },
    scListItem: { flex: 1, fontSize: 12, color: t.inkFaint },
    scListPrice: {
      fontFamily: mono,
      fontWeight: '800',
      fontSize: 13.5,
      color: t.brand,
      fontVariant: ['tabular-nums'],
    },

    /* ===== clean rebuild: category + ranked stores ===== */
    h1clean: { fontFamily: sans.xbold, fontSize: 24, letterSpacing: -0.5, color: t.ink },
    listHint: {
      paddingHorizontal: 18,
      marginTop: 18,
      marginBottom: 10,
      fontSize: 13,
      color: t.inkFaint,
      fontWeight: '600',
    },
    emptyLine: { paddingHorizontal: 18, paddingVertical: 18, color: t.inkSoft, fontSize: 14, lineHeight: 21 },

    rankRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 13,
      marginHorizontal: 18,
      marginBottom: 10,
      backgroundColor: t.surface,
      borderWidth: 1,
      borderColor: t.line,
      borderRadius: 14,
      paddingVertical: 14,
      paddingHorizontal: 15,
    },
    rankRowTop: { borderColor: t.brand, borderWidth: 1.5 },
    rankNum: {
      width: 30, height: 30, borderRadius: 15,
      backgroundColor: t.surface2, alignItems: 'center', justifyContent: 'center',
    },
    rankNumTop: { backgroundColor: t.brand },
    rankNumText: { fontFamily: mono, fontWeight: '800', fontSize: 14, color: t.inkSoft },
    rankNumTextTop: { color: '#fff' },
    rankMid: { flex: 1, gap: 2 },
    rankStore: { fontSize: 16, fontWeight: '700', color: t.ink },
    rankSub: { fontSize: 12.5, color: t.inkFaint },
    rankRight: { alignItems: 'flex-end' },
    rankPrice: { fontFamily: mono, fontWeight: '800', fontSize: 16, color: t.ink, fontVariant: ['tabular-nums'] },
    rankPriceTop: { color: t.brand },
    rankDist: { fontSize: 11.5, color: t.inkFaint, marginTop: 2 },
    cheapestTag: {
      alignSelf: 'flex-start',
      backgroundColor: t.brandSoft,
      borderRadius: 6,
      paddingHorizontal: 7,
      paddingVertical: 2,
      marginTop: 3,
    },
    cheapestTagText: { fontFamily: mono, fontSize: 9, letterSpacing: 0.5, color: t.brandInk, fontWeight: '700' },

    /* clean store card (Stores tab) */
    storeCard2: {
      marginHorizontal: 18,
      marginBottom: 12,
      backgroundColor: t.surface,
      borderWidth: 1,
      borderColor: t.line,
      borderRadius: 14,
      padding: 16,
    },
    storeCard2Top: { flexDirection: 'row', alignItems: 'baseline', gap: 8 },
    storeCard2Name: { fontFamily: sans.xbold, fontSize: 17, color: t.ink, flex: 1 },
    storeCard2Dist: { fontFamily: mono, fontSize: 13, color: t.inkFaint },
    storeCard2Meta: { fontSize: 12.5, color: t.inkFaint, marginTop: 2, marginBottom: 4 },

    /* prominent location header (Stores tab) */
    locHeader: {
      paddingHorizontal: 20,
      paddingBottom: 14,
      backgroundColor: t.surface,
      borderBottomWidth: 1,
      borderBottomColor: t.line,
    },
    locHeaderCity: { fontFamily: sans.xbold, fontSize: 25, color: t.ink, letterSpacing: -0.5 },
    locHeaderChevron: { fontSize: 16, color: t.inkSoft, fontWeight: '600' },
    locHeaderSub: { fontSize: 13.5, color: t.inkFaint, marginTop: 4 },

    /* location popup */
    modalBackdrop: { flex: 1, backgroundColor: 'rgba(0,0,0,0.45)', justifyContent: 'flex-end' },
    modalSheet: {
      backgroundColor: t.surface,
      borderTopLeftRadius: 22,
      borderTopRightRadius: 22,
      paddingHorizontal: 20,
      paddingTop: 10,
    },
    modalHandle: {
      alignSelf: 'center',
      width: 40,
      height: 5,
      borderRadius: 3,
      backgroundColor: t.lineStrong,
      marginBottom: 16,
    },
    modalTitle: { fontFamily: sans.xbold, fontSize: 20, color: t.ink, marginBottom: 16 },
    sliderRow: {
      flexDirection: 'row',
      alignItems: 'baseline',
      justifyContent: 'space-between',
      marginTop: 22,
      marginBottom: 2,
    },
    sliderLabel: { fontSize: 15, fontWeight: '700', color: t.ink },
    sliderValue: { fontFamily: mono, fontSize: 16, fontWeight: '800', color: t.brand },
    modalDone: {
      backgroundColor: t.ink,
      borderRadius: 12,
      paddingVertical: 14,
      alignItems: 'center',
      marginTop: 20,
    },
    modalDoneText: { color: t.paper, fontWeight: '800', fontSize: 15 },

    /* footer */
    footer: { marginTop: 30, alignItems: 'center' },
    footerNote: { fontSize: 12.5, lineHeight: 19, color: t.inkFaint, textAlign: 'center' },
    footerDisc: {
      marginTop: 14,
      fontFamily: mono,
      fontSize: 10,
      lineHeight: 17,
      color: t.inkFaint,
      textAlign: 'center',
    },
  });
}
